plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.graalvm.buildtools.native' version '0.10.4'
    id 'com.google.protobuf' version '0.9.4'
    id "org.sonarqube" version "7.1.0.6387"
    id 'jacoco'

}

group = 'com.graalvm'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // imperative normal springboot ( needed for SOAP)
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-web-services'
    implementation 'wsdl4j:wsdl4j'
    // WebFlux (reactive web, includes reactive WebSocket support)
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    // Reactive data with R2DBC
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    // H2 R2DBC driver (available at runtime AND test)
    runtimeOnly 'io.r2dbc:r2dbc-h2'
    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Swagger for Rest webflux
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.6.0'


    //grapahana, tempo and prometheus imports
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
    //kafka
    implementation 'io.projectreactor.kafka:reactor-kafka'
    // protobuf 
    implementation 'com.google.protobuf:protobuf-java:3.25.1'
    // needed for working with json for websocket
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    

}

tasks.named('test') {
    useJUnitPlatform()
}
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.1'
    }
}


jacocoTestReport {
    reports {
        xml.required = true
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                '**/test/**',
                '**/*Test*',
                '**/*Tests*',
                '**/*Base*',
                '**/model/**',
                '**/config/**',
                '**/unitary/**',
                '**/regression/**',
                '**/integration/**'
            ])
        }))
    }
}



def env = file('.env').readLines()
    .findAll { it.contains('=') && !it.startsWith('#') }
    .collectEntries { line ->
        def (key, value) = line.split('=', 2)
        [key.trim(), value.trim()]
    }

sonar {
    properties {
        property "sonar.projectKey", env['SONAR_PROJECTKEY']
        property "sonar.host.url", env['SONAR_URL']
        property "sonar.token", env['SONAR_TOKEN']
        property "sonar.coverage.exclusions", "**/test/**,**/*Test*,**/*Tests*,**/*Base*,**/model/**,**/config/**"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
    
    }
}
