spring.application.name=compilationTEST
spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.var.entorno=${DB_URL:r2dbc:h2:mem:///testdb}
spring.r2dbc.pool.initial-size=20
spring.r2dbc.pool.max-size=50
// remove before flight
spring.sql.init.mode=always